sudo: false

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

script:
  - tox
  - tox -e lint

deploy:
  provider: pypi
  user: ahmet2mir
  password:
    secure: 10oj8tm6r6yBhkWYUESOvkmUY41zpUNhxh+2Mhw8VRQ5fpBiWqk6XCTB189oU2B00H1la/yFql++Cz6D2SPIO4Z+1ufkk+gjXEebgbhyxheKXKdbTNyCb2iAfuR9HzZJhb6O6VSxs9btQyGKLPcPzwjDf/s18yMZQCD9cIFrMqj+vZRBXtTtMUA3o5gxMfYrD/z+sNkPNCfrhIm8uFNDcOezza/j50BYicXfbNfs+NUKXuMg3QwN6NXvz+kQ5QnzWcAsNiKcOlB8nrkG77F9eP2WLEDiXWgwY0nn9uXAWd7yiB/4yX+AdaX1JhLz3nuH4CWu92ZWwOwZbkvIwCaoBd5dnsQZQ/Jrr8syfl1Eh+hqutZ2u0K5OHczQln6m9wjph/P7n1cSSiHdhW4SIs1OP2kSAh08EjDEVhTKCy1egXEKgAl6Z5BPaVtVzgXy2kpScp9uelTVHpibKhf8mfXoFL+C3pe3OTpMVVhOL3rKyL2IbQp+BAE1ZD1N+4TjF2m14bJ+kgGaz2wOlNfWyE8vXjqF10jocI7bWHOyD+ocCfhxYDUKA6LPN3QIVJ159orGGuV21hL19dk6bNZUbR6//7mavFXR2qV1t3EwDQQ2Od5xdeQbhlddAr8IYT9E9LWqitQvgHz0HYvnDLmHJNNcfSi+SUF0O9Ka70OzOM4N+8=
